import Head from "next/head";
import Header from "../components/Header";
import Navbar from "../components/Navbar";
import Results from "../components/Results";
import { requests } from "../requests";

export default function Home({ datas }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Navbar />
      <Results datas={datas} />
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre || "fetchTrending";

  const fetchData = await fetch(
    `https://api.themoviedb.org/3${requests[genre].url}`
  ).then((response) => response.json());

  return {
    props: { datas: fetchData },
  };
}
